// Generated by gencpp from file lab2/mux_control.msg
// DO NOT EDIT!


#ifndef LAB2_MESSAGE_MUX_CONTROL_H
#define LAB2_MESSAGE_MUX_CONTROL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace lab2
{
template <class ContainerAllocator>
struct mux_control_
{
  typedef mux_control_<ContainerAllocator> Type;

  mux_control_()
    : header()
    , state(0)  {
    }
  mux_control_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , state(0)  {
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int8_t _state_type;
  _state_type state;




  typedef boost::shared_ptr< ::lab2::mux_control_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lab2::mux_control_<ContainerAllocator> const> ConstPtr;

}; // struct mux_control_

typedef ::lab2::mux_control_<std::allocator<void> > mux_control;

typedef boost::shared_ptr< ::lab2::mux_control > mux_controlPtr;
typedef boost::shared_ptr< ::lab2::mux_control const> mux_controlConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::lab2::mux_control_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::lab2::mux_control_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace lab2

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'lab2': ['/home/kaitlyn/Desktop/Git_Repos/Fanboat/src/lab2/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::lab2::mux_control_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lab2::mux_control_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lab2::mux_control_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lab2::mux_control_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lab2::mux_control_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lab2::mux_control_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::lab2::mux_control_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6b8ba4e04f882f0e14fe3dd848d01f25";
  }

  static const char* value(const ::lab2::mux_control_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6b8ba4e04f882f0eULL;
  static const uint64_t static_value2 = 0x14fe3dd848d01f25ULL;
};

template<class ContainerAllocator>
struct DataType< ::lab2::mux_control_<ContainerAllocator> >
{
  static const char* value()
  {
    return "lab2/mux_control";
  }

  static const char* value(const ::lab2::mux_control_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::lab2::mux_control_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
\n\
int8 state\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::lab2::mux_control_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::lab2::mux_control_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.state);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct mux_control_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lab2::mux_control_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::lab2::mux_control_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "state: ";
    Printer<int8_t>::stream(s, indent + "  ", v.state);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LAB2_MESSAGE_MUX_CONTROL_H
