// Generated by gencpp from file lab2/toggle.msg
// DO NOT EDIT!


#ifndef LAB2_MESSAGE_TOGGLE_H
#define LAB2_MESSAGE_TOGGLE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace lab2
{
template <class ContainerAllocator>
struct toggle_
{
  typedef toggle_<ContainerAllocator> Type;

  toggle_()
    : toggle(false)  {
    }
  toggle_(const ContainerAllocator& _alloc)
    : toggle(false)  {
    }



   typedef uint8_t _toggle_type;
  _toggle_type toggle;




  typedef boost::shared_ptr< ::lab2::toggle_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lab2::toggle_<ContainerAllocator> const> ConstPtr;

}; // struct toggle_

typedef ::lab2::toggle_<std::allocator<void> > toggle;

typedef boost::shared_ptr< ::lab2::toggle > togglePtr;
typedef boost::shared_ptr< ::lab2::toggle const> toggleConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::lab2::toggle_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::lab2::toggle_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace lab2

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'lab2': ['/home/kaitlyn/Desktop/Git_Repos/Fanboat/src/lab2/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::lab2::toggle_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lab2::toggle_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lab2::toggle_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lab2::toggle_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lab2::toggle_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lab2::toggle_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::lab2::toggle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "301e9e6fc0ec5b2acb90ccde2488159e";
  }

  static const char* value(const ::lab2::toggle_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x301e9e6fc0ec5b2aULL;
  static const uint64_t static_value2 = 0xcb90ccde2488159eULL;
};

template<class ContainerAllocator>
struct DataType< ::lab2::toggle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "lab2/toggle";
  }

  static const char* value(const ::lab2::toggle_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::lab2::toggle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool toggle\n\
";
  }

  static const char* value(const ::lab2::toggle_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::lab2::toggle_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.toggle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct toggle_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lab2::toggle_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::lab2::toggle_<ContainerAllocator>& v)
  {
    s << indent << "toggle: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.toggle);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LAB2_MESSAGE_TOGGLE_H
