// Generated by gencpp from file fanboat_ll/fanboatMotors.msg
// DO NOT EDIT!


#ifndef FANBOAT_LL_MESSAGE_FANBOATMOTORS_H
#define FANBOAT_LL_MESSAGE_FANBOATMOTORS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace fanboat_ll
{
template <class ContainerAllocator>
struct fanboatMotors_
{
  typedef fanboatMotors_<ContainerAllocator> Type;

  fanboatMotors_()
    : header()
    , left(0.0)
    , right(0.0)  {
    }
  fanboatMotors_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , left(0.0)
    , right(0.0)  {
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _left_type;
  _left_type left;

   typedef double _right_type;
  _right_type right;




  typedef boost::shared_ptr< ::fanboat_ll::fanboatMotors_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::fanboat_ll::fanboatMotors_<ContainerAllocator> const> ConstPtr;

}; // struct fanboatMotors_

typedef ::fanboat_ll::fanboatMotors_<std::allocator<void> > fanboatMotors;

typedef boost::shared_ptr< ::fanboat_ll::fanboatMotors > fanboatMotorsPtr;
typedef boost::shared_ptr< ::fanboat_ll::fanboatMotors const> fanboatMotorsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::fanboat_ll::fanboatMotors_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::fanboat_ll::fanboatMotors_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace fanboat_ll

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'fanboat_ll': ['/home/alexanderrenken/Fanboat/src/fanboat_ll/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::fanboat_ll::fanboatMotors_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fanboat_ll::fanboatMotors_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fanboat_ll::fanboatMotors_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fanboat_ll::fanboatMotors_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fanboat_ll::fanboatMotors_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fanboat_ll::fanboatMotors_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::fanboat_ll::fanboatMotors_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8f32685125452f5bdf68130369af5296";
  }

  static const char* value(const ::fanboat_ll::fanboatMotors_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8f32685125452f5bULL;
  static const uint64_t static_value2 = 0xdf68130369af5296ULL;
};

template<class ContainerAllocator>
struct DataType< ::fanboat_ll::fanboatMotors_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fanboat_ll/fanboatMotors";
  }

  static const char* value(const ::fanboat_ll::fanboatMotors_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::fanboat_ll::fanboatMotors_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
\n\
#Current settings of the motors [-1.0,1.0]\n\
#negative is reverse (if available), 0.0 stop, positive forward\n\
float64 left\n\
float64 right\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::fanboat_ll::fanboatMotors_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::fanboat_ll::fanboatMotors_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.left);
      stream.next(m.right);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct fanboatMotors_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::fanboat_ll::fanboatMotors_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::fanboat_ll::fanboatMotors_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "left: ";
    Printer<double>::stream(s, indent + "  ", v.left);
    s << indent << "right: ";
    Printer<double>::stream(s, indent + "  ", v.right);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FANBOAT_LL_MESSAGE_FANBOATMOTORS_H
